### PR TITLE
Mimic numpy's norm when ord is None

### PR DESCRIPTION
**Pull request by kaushikcfd**
- When ord is None, numpy ravels the array and then computes the euclidean norm.

I couldn't find a mention for this in the numpy docs, but here is a small script:
```python
In [2]: a = np.random.rand(3, 3, 3, 3, 3)

In [3]: np.linalg.norm(a)
Out[3]: 8.718438810223871

In [4]: np.linalg.norm(a.ravel(), ord=2)
Out[4]: 8.718438810223871
```

Let me know what do you guys think.

### CODE REVIEW

**Comment by inducer** [comment]
Thanks! If you add a test showing that the behavior matches numpy, I could see going along with this. @alexfikl?

**Comment by kaushikcfd** [comment]
> If you add a test showing that the behavior matches numpy

Done! See 1bae084.

**Comment by alexfikl** [comment]
> Thanks! If you add a test showing that the behavior matches numpy, I could see going along with this. @alexfikl?

Yeah, this should match the [docs for linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
```
If both axis and ord are None, the 2-norm of x.ravel will be returned.
```

**Comment by inducer** [comment]
LGTM. Thanks!

**Pull request merged**
