### PR TITLE
Expose types for subpackages in package root

### PR DESCRIPTION
**Pull request by inducer**
This exposes a few type things in the root so that subpacakges can be fixed, as described here: https://github.com/inducer/arraycontext/pull/181#issuecomment-1170378680.

### CODE REVIEW

**Comment by alexfikl** [comment]
From a quick grep, meshmode also needs `from .context import ArrayT`

**Comment by inducer** [comment]
Added `Array` and `ArrayT`.

**Comment by inducer** [comment]
(Make sure to change to `Array`, not `ArrayT`, when things aren't required to be a type variable.)

**Comment by inducer** [comment]
Let's call this finished and add more commits later if needed.

**Comment by inducer** [comment]
I've just gone ahead and force-merged this so that we can move on with life. :)

**Pull request merged**
