### PR TITLE
Add typing to ArrayContext

### PR DESCRIPTION
**Pull request by alexfikl**
This uses the new `Array` and `Scalar` protocols to add some type annotations to `ArrayContext`.

What other places did you have in mind in https://github.com/inducer/arraycontext/pull/153#discussion_r843365012? I looked a bit through the container stuff, but they're all nested, so there aren't many places where it makes sense to use these.

### CODE REVIEW

**Comment by inducer** [comment]
Thanks! I'll hold off on a review until after https://github.com/inducer/pytools/pull/124.

**Comment by inducer** [comment]
https://pypi.org/project/pytools/2022.1.3/

**Comment by inducer** [comment]
Yep, sorry. Forgot to push that!

**Comment by inducer** [comment]
(now done)

**Comment by alexfikl** [comment]
Thank you!

**Pull request merged**
